learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.conf.urls import url

from . import views

urlpatterns = [

    # 主页
    url(r'^$', views.index, name='index'),

    # 显示所有的主题
    url(r'^topics/$', views.topics, name='topics'),

    # 显示特定主题的详细页面
    url(r'^topics/(?P<topic_id>[0-9]+)/$', views.topic, name='topic'),

    # 用于添加新主题的页面
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # 用于添加对应主题中新文章的页面

    url(r'^new_entry/(?P<topic_id>[0-9]+)/$', views.new_entry, name='new_entry'),

    # 用于编辑现有的文章
    url(r'^edit_entry/(?P<entry_id>[0-9]+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    # 登陆页面，使用的默认视图login
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

    # 注销
    url(r'^logout/$', views.logout_view, name='logout'),

    # 注册页面
    url(r'^register/$', views.register, name='register'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    """用户学习的主题"""

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到的有关某个主题的具体知识"""

    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50] + '... '

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    """Topic的表单"""

    # Meta类是告诉Django根据哪个模型创建表单，以及在表单中包含哪些字段
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
# coding:utf-8

from django.shortcuts import render
from .models import Topic, Entry
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404


# Create your views here.

def index(request):
    """学习笔记的主页"""

    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """显示所有的主题"""

    tps = Topic.objects.filter(owner=request.user).order_by('-date_added')

    context = {'topics': tps}

    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """显示特定主题的所有条目的详细页面"""
    tp = Topic.objects.get(id=topic_id)

    # 确定请求的主题属于当前用户
    if tp.owner != request.user:
        raise Http404
    else:
        entries = tp.entry_set.order_by('-date_added')
        context = {'topic': tp, 'entries': entries}
        return render(request, 'learning_logs/topic.html', context)


# 处理刚进入状态和提交表单后重定向到topics
@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据；创建一个新表单
        form = TopicForm
    else:
        # POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """在特定主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # 未提交数据,创建空表单
        form = EntryForm()
    else:
        # POST提交数据
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic

            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """编辑现有的文章"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # 第一次请求，用当前的条目填充表单
        form = EntryForm(instance=entry)
    else:
        # 修改后POST重新提交文章
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """注销用户"""

    logout(request)

    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        # 处理填写的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登陆，并重定向到主页
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])

            login(request, authenticated_user)

            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}

    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
    <title>Fighting Frank's Blog</title>
    {% endblock title %}
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

<!-- Static navbar -->
    <nav class="nabar navbar-default navbar-static-top">
        <div class="container">

            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar"></button>

                {% if user.is_authenticated %}

                    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">{{user.username}} Blog</a>
                {% else %}
                    <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Blog</a>
                {% endif %}
            </div>



            <div id="navbar" class="navbar-collapse collapse">

               <ul class="nav navbar-nav">

                 <li>
                        <a href="{% url 'learning_logs:topics' %}">Topics</a>
                 </li>
               </ul>


               <ul class="nav navbar-nav navbar-right">
                   {% if user.is_authenticated %}
                        <li><a>Hello,{{user.username}}.</a></li>
                        <li><a href="{% url 'users:logout' %}">Log out</a></li>
                    {% else %}
                        <li><a href="{% url 'users:register' %}">Register</a></li>
                        <li><a href="{% url 'users:login' %}">Login</a></li>
                    {% endif %}
               </ul>


            </div> <!-- /.nav-collapse-->
        </div>

    </nav>

    <div class="container">


        <div class="page-header">
            {% block header %}
            {% endblock header %}
        </div>

        <div>
            {% block content %}
            {% endblock content %}

        </div>
    </div>  <!-- /container -->



</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Blog</title>
</head>
<body>

    {% extends 'learning_logs/base.html' %}
    {% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Edit Entry</p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">save changes</button>

    </form>

{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends 'learning_logs/base.html' %}
    {% block title %}
        {% if user.is_authenticated %}
            <title>{{ user.username }} Blog</title>
        {% else %}
            <title>Learning Blog</title>
        {% endif %}

    {% endblock title %}
</head>
<body>


    {% block header %}

        <div class="jumbotron">

            <h1>Track your learning</h1>

        </div>

    {% endblock header %}

    {% block content %}

        <h2>
            <a href="{% url 'users:register' %}">Register an account</a> to make your own
            learning blog, and list the topics you're learning about.

        </h2>
        <h2>
            Whenever you learn something new about a topic, make an entry summarizing what you've learned.
        </h2>
    {% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加博文</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add entry</button>

    </form>

{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add_Topic</title>
</head>
<body>

    {% extends 'learning_logs/base.html' %}
    {% load bootstrap3 %}

    {% block header %}

        <h2>
           Add a new Topic:

        </h2>

    {% endblock header %}

    {% block content %}

    <form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}

            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}

    </form>

    {% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topic</title>
</head>
<body>

    {% extends 'learning_logs/base.html' %}
    {% load bootstrap3 %}

    {% block header %}

        <h2><p>Topic: {{topic}}</p></h2>
    {% endblock header %}

    {% block content %}

        <h3><p>Blogs:</p></h3>


        <p>
            <a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a>
        </p>


        {% for entry in entries %}
            <div class="panel panel-default">
                <div class="panel-heading">

                    <h3>
                        {{ entry.date_added|date:'M,d,Y H:i' }}
                        <small>

                            <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit Blog</a>
                        </small>

                    </h3>

                </div>

                <div class="panel-body">
                    {{ entry.text|linebreaks }}

                </div>


            </div> <!-- panel -->
        {% empty %}

            There are no entries for this topic yet.

        {% endfor %}



{% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block header %}

        <h1>Topics</h1>
    {% endblock header %}

    {% block content %}

        <ul>
            {% for topic in topics %}

                <li>

                    <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3>
                </li>
            {% empty %}

                <li>No topics have been added yet.</li>

            {% endfor %}
        </ul>

        <h3><a href="{% url 'learning_logs:new_topic' %}">Add New Topic:</a></h3>

    {% endblock content %}

</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% load bootstrap3 %}

    {% block header %}
        <h2>
            Login your account.
        </h2>
    {% endblock header %}


    {% block content %}

    <form action="{% url 'users:login' %}" method="POST" class="form">

        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}

            <button name="submit" class="btn btn-primary">Login</button>

        {% endbuttons %}

        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />

    </form>
    {% endblock content %}
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>

    {% extends 'learning_logs/base.html' %}
    {% block content %}

        <form action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button name="submit">注册</button>
            <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />

        </form>
    {% endblock content %}
</body>
</html>